name: Build gecko-dev immediately

on:
  workflow_dispatch:

env:
  SFOS_RELEASE: 4.5.0.21

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Prepare
      run: mkdir -p RPMS
      
    - name: Build
      uses: robang74/github-sfos-apps-build@master
      with:
        release: ${{ env.SFOS_RELEASE }}
        arch: ${{ env.ARCH }}
        spec_file: rpm/xulrunner-qt5.spec

    - name: Upload build results
      uses: actions/upload-artifact@v3
      with:
        name: RPMS build results
        path: RPMS
